class ProductService {
    public findProducts():any[] {
        return [
            {
                conteudo: '750 ML',
                descricao: 'Whisky Johnnie Walker Blue Label 750 ML',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/043/full/jw.jpg?1548453632',
                id: '1',
                ingredientes: 'Cevada, Malte, Grãos e Água.',
                nome: 'Johnnie Walker',
                origem: 'Escócia',
                sabor: 'tradicional',
                valor: 268.12,
                versao: 'Blue Label',
                tipo:'W',
            },
            {
                conteudo: '750ml',
                descricao: 'Whisky Grand Old Parr Escocês 12 Anos 750ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/047/full/op.jpg?1548453832',
                id: '2',
                ingredientes: 'Cevada, Malte, Grãos e Água.',
                nome: 'Grand Old Parr',
                origem: 'Escócia',
                sabor: 'tradicional',
                valor: 144.00,
                versao: 'Tradicional',
                tipo:'W',
            },
            {
                conteudo: '1000ml',
                descricao: 'Whisky Chivas Regal Escocês 12 Anos 1 Litro',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/056/full/cr.jpg?1548454158',
                id: '3',
                ingredientes: 'Água, Grãos e Malte.',
                nome: 'Chivas Regal',
                origem: 'Escócia',
                sabor: 'tradicional',
                valor: 109.90,
                versao: '12 Anos',
                tipo:'W',
            },
            {
                conteudo: '1000ml',
                descricao: 'Whisky White Horse 1 Litro',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/063/full/wh.jpg?1548454496',
                id: '4',
                ingredientes: 'Cevada, Malte, Grãos e Água.',
                nome: 'White Horse',
                origem: 'Escócia',
                sabor: 'tradicional',
                valor: 67.39,
                versao: 'Tradicional',
                tipo:'W',
            },
            {
                conteudo: '1000ml',
                descricao: 'Whisky Ballantine\'s Finest Escocês 1 Litro',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/069/full/b.jpg?1548454748',
                id: '5',
                ingredientes: 'Água, Cevada, outros Cereais e Leveduras.',
                nome: 'Ballantine\'s',
                origem: 'Escócia',
                sabor: 'tradicional',
                valor: 85.99,
                versao: 'Finest',
                tipo:'W',
            },
            {
                conteudo: '1000ml',
                descricao: 'Whisky Passport Scotch Escocês 1 Litro',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/089/full/ps.jpg?1548455496',
                id: '6',
                ingredientes: 'Água, Cevada, Cereais e Leveduras.',
                nome: 'Passport Scotch',
                origem: 'Escócia',
                sabor: 'tradicional',
                valor: 465.99,
                versao: 'tradicional',
                tipo:'W',
            },
            {
                conteudo: '1000ml',
                descricao: 'Whisky Buchanan\'s de Luxe 12 Anos 1 Litro',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/095/full/b2.jpg?1548455709',
                id: '7',
                ingredientes: 'Cevada, Malte, Grãos e Água',
                nome: 'Passport Scotch',
                origem: 'Escócia',
                sabor: 'tradicional',
                valor: 155.00,
                versao: '12 Anos',
                tipo:'W',
            },
            {
                conteudo: '1000ml',
                descricao: 'Whisky Grant\'s Escocês 8 Anos 1 Litro',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/104/full/g.jpg?1548455907',
                id: '8',
                ingredientes: 'Cevada, Malte, Grãos e Água',
                nome: 'Grant\'s',
                origem: 'Escócia',
                sabor: 'tradicional',
                valor: 80.49,
                versao: '8 Anos',
                tipo:'W',
            },
            {
                conteudo: '998ml',
                descricao: 'Vodka Smirnoff Red 998ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/127/full/soff.jpg?1548456714',
                id: '9',
                ingredientes: 'Trigo, Aveia,Cevada, Malte, Água',
                nome: 'Grant\'s',
                origem: 'Rússia',
                sabor: 'tradicional',
                valor: 32.89,
                versao: 'Red',
                tipo:'V',
            },
            {
                conteudo: '750ml',
                descricao: 'Vodka Ciroc Premium 750ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/193/full/cir.jpg?1548458680',
                id: '10',
                ingredientes: 'Trigo, Aveia, Cevada, Malte, Água',
                nome: 'Ciroc',
                origem: 'França',
                sabor: 'tradicional',
                valor: 129.00,
                versao: 'Premium',
                tipo:'V',
            },              
            {
                conteudo: '750ml',
                descricao: 'Vodka Absolut Original 750ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/196/full/abs.jpg?1548458864',
                id: '11',
                ingredientes: 'Trigo de inverno e água',
                nome: 'Absolut',
                origem: 'Suécia',
                sabor: 'tradicional',
                valor: 64.90,
                versao: 'Original',
                tipo:'V',
            },              
            {
                conteudo: '1000ml',
                descricao: 'Vodka Orloff Nacional 1 Litro',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/200/full/or.jpg?1548459063',
                id: '12',
                ingredientes: 'Água e destilado de cana de açúcar',
                nome: 'Orloff',
                origem: 'Brasil',
                sabor: 'tradicional',
                valor: 26.90,
                versao: 'Nacional',
                tipo:'V',
            },    
            {
                conteudo: '980ml',
                descricao: 'Vodka Skyy 980ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/208/full/sky.jpg?1548459319',
                id: '13 ',
                ingredientes: 'Destilado de arroz, Cereais.',
                nome: 'Skyy',
                origem: 'Brasil',
                sabor: 'tradicional',
                valor: 34.89,
                versao: 'Nacional',
                tipo:'V',
            },
            {
                conteudo: '980ml',
                descricao: 'Cachaça Ypióca 160 Anos 700ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/224/full/nf.jpg?1548459682',
                id: '14 ',
                ingredientes: '',
                nome: 'Ypióca',
                origem: 'Brasil',
                sabor: 'tradicional',
                valor: 89.90,
                versao: '160 Anos',
                tipo:'C',
            },
            {
                conteudo: '750ml',
                descricao: 'Cachaça Busca Vida Mel e Limão Premium 750ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/229/full/c_bf.jpg?1548459829',
                id: '15 ',
                ingredientes: 'Cachaça, Limão, Mel, Açúcar.',
                nome: 'Busca Vida',
                origem: 'Brasil',
                sabor: 'Mel Limão',
                valor: 82.99,
                versao: 'Premium',
                tipo:'C',
            },
            {
                conteudo: '700ml',
                descricao: 'Cachaça Salinas Tradicional 700ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/232/full/sal.jpg?1548459952',
                id: '16 ',
                ingredientes: 'Mosto fermentado do caldo de cana-de-açúcar.',
                nome: 'Salinas',
                origem: 'Brasil',
                sabor: 'Tradicional',
                valor: 43.99,
                versao: 'Tradicional',
                tipo:'C',
            },
            {
                conteudo: '750ml',
                descricao: 'Cachaça Nêga Fulô 700ml',
                embalagem: 'Garrafa',
                foto: 'https://uploaddeimagens.com.br/images/001/857/233/full/nega.jpg?1548460004',
                id: '17',
                ingredientes: 'Mosto fermentado do caldo de cana-de-açúcar.',
                nome: 'Nêga Fulô',
                origem: 'Brasil',
                sabor: 'Tradicional',
                valor: 99.49,
                versao: 'Tradicional',
                tipo:'C',
            },
        ];
    }

    public findProductsById(ID: string):any {
        return this.findProducts().find(p => p.id === ID);
    }

}

export default ProductService;