
const CartConstants = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    REMOVE_ALL: 'REMOVE_ALL',
    INCREASE_PRODUCT_QUANTITY: 'INCREASE_PRODUCT_QUANTITY',
    DECREASE_PRODUCT_QUANTITY: 'DECREASE_PRODUCT_QUANTITY'
}

export default CartConstants;
